adjust ci

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -20,4 +20,8 @@ jobs:
         run: docker run app vendor/bin/psalm
       - name: Test ambiguous-classes
         run: |
+          set -ex
           docker run app bin/ambiguous-classes dummy/ambigious-classes/without-errors
+          # We negate the exit code, because we expect an error
+          docker run app bin/ambiguous-classes dummy/ambigious-classes/with-errors || exit 0
+          
